const harleyMornings = [
  {
    sleep: '6-8',
    social: 'Not at all',
    sun: 3,
    relax: 'More than usual',
    exercise: false,
    work: 3,
    meals: 3,
    pleasant: 0.83,
    tension: 0.37,
    energy: 0.38,
    date: '2019-02-07',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Less than usual',
    sun: 4,
    relax: 'Less than usual',
    exercise: false,
    work: 3,
    meals: 3,

    pleasant: 0.21,
    tension: 0.94,
    energy: 0.21,
    date: '2019-02-08',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 4,
    relax: 'More than usual',
    exercise: false,
    work: 3,
    meals: 1,

    pleasant: 0.82,
    tension: 0.79,
    energy: 0.86,
    date: '2019-02-09',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'More than usual',
    sun: 1,
    relax: 'Usual amount',
    exercise: false,
    work: 3,
    meals: 0,

    pleasant: 0.78,
    tension: 0.81,
    energy: 0.13,
    date: '2019-02-10',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 5,
    relax: 'Usual amount',
    exercise: false,
    work: 5,
    meals: 3,

    pleasant: 0.85,
    tension: 0.49,
    energy: 0.4,
    date: '2019-02-11',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Less than usual',
    sun: 3,
    relax: 'Usual amount',
    exercise: false,
    work: 4,
    meals: 1,

    pleasant: 0.75,
    tension: 0.34,
    energy: 0.92,
    date: '2019-02-12',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 2,
    relax: 'Less than usual',
    exercise: false,
    work: 4,
    meals: 3,

    pleasant: 0.72,
    tension: 0.74,
    energy: 0.62,
    date: '2019-02-13',
    userId: 3
  },
  {
    sleep: '4-6',
    social: 'Less than usual',
    sun: 4,
    relax: 'Less than usual',
    exercise: false,
    work: 3,
    meals: 2,

    pleasant: 0.66,
    tension: 0.35,
    energy: 0.7,
    date: '2019-02-14',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'More than usual',
    sun: 4,
    relax: 'Not at all',
    exercise: false,
    work: 4,
    meals: 3,

    pleasant: 0.58,
    tension: 0.94,
    energy: 0.83,
    date: '2019-02-15',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Not at all',
    sun: 3,
    relax: 'More than usual',
    exercise: false,
    work: 0,
    meals: 2,

    pleasant: 0.75,
    tension: 0.13,
    energy: 0.63,
    date: '2019-02-16',
    userId: 3
  },
  {
    sleep: '4-6',
    social: 'More than usual',
    sun: 4,
    relax: 'Less than usual',
    exercise: false,
    work: 3,
    meals: 2,

    pleasant: 0.68,
    tension: 0.85,
    energy: 0.6,
    date: '2019-02-17',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 3,
    relax: 'Less than usual',
    exercise: true,
    work: 5,
    meals: 4,

    pleasant: 0.6,
    tension: 0.53,
    energy: 0.69,
    date: '2019-02-18',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'More than usual',
    sun: 2,
    relax: 'Usual amount',
    exercise: true,
    work: 5,
    meals: 3,

    pleasant: 1,
    tension: 0.87,
    energy: 0.69,
    date: '2019-02-19',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 3,
    relax: 'Usual amount',
    exercise: false,
    work: 4,
    meals: 2,

    pleasant: 0.75,
    tension: 0.69,
    energy: 0.49,
    date: '2019-02-20',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 0,
    relax: 'Usual amount',
    exercise: false,
    work: 3,
    meals: 3,

    pleasant: 0.61,
    tension: 0.97,
    energy: 1,
    date: '2019-02-21',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Less than usual',
    sun: 0,
    relax: 'Usual amount',
    exercise: true,
    work: 4,
    meals: 2,

    pleasant: 0.91,
    tension: 0.26,
    energy: 0.85,
    date: '2019-02-22',
    userId: 3
  },
  {
    sleep: '4-6',
    social: 'Usual amount',
    sun: 5,
    relax: 'Less than usual',
    exercise: true,
    work: 5,
    meals: 1,

    pleasant: 0.88,
    tension: 0.88,
    energy: 0.92,
    date: '2019-02-23',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 3,
    relax: 'Less than usual',
    exercise: false,
    work: 3,
    meals: 3,

    pleasant: 0.71,
    tension: 0.65,
    energy: 0.63,
    date: '2019-02-24',
    userId: 3
  },
  {
    sleep: '2-4',
    social: 'Usual amount',
    sun: 2,
    relax: 'Usual amount',
    exercise: false,
    work: 3,
    meals: 3,

    pleasant: 0.69,
    tension: 0.6,
    energy: 0.25,
    date: '2019-02-25',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 5,
    relax: 'Less than usual',
    exercise: false,
    work: 4,
    meals: 2,

    pleasant: 0.72,
    tension: 0.56,
    energy: 0.66,
    date: '2019-02-26',
    userId: 3
  },
  {
    sleep: '0-2',
    social: 'Less than usual',
    sun: 3,
    relax: 'More than usual',
    exercise: false,
    work: 3,
    meals: 2,

    pleasant: 0.65,
    tension: 0.35,
    energy: 0.36,
    date: '2019-02-27',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Less than usual',
    sun: 4,
    relax: 'Less than usual',
    exercise: true,
    work: 3,
    meals: 2,

    pleasant: 0.77,
    tension: 0.34,
    energy: 0.75,
    date: '2019-02-28',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 5,
    relax: 'Less than usual',
    exercise: true,
    work: 3,
    meals: 3,

    pleasant: 0.92,
    tension: 0.71,
    energy: 0.58,
    date: '2019-03-01',
    userId: 3
  },
  {
    sleep: '2-4',
    social: 'More than usual',
    sun: 4,
    relax: 'Less than usual',
    exercise: false,
    work: 2,
    meals: 3,

    pleasant: 0.55,
    tension: 0.87,
    energy: 0.53,
    date: '2019-03-02',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 4,
    relax: 'Less than usual',
    exercise: false,
    work: 4,
    meals: 3,

    pleasant: 0.62,
    tension: 0.46,
    energy: 0.28,
    date: '2019-03-03',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Not at all',
    sun: 3,
    relax: 'More than usual',
    exercise: false,
    work: 3,
    meals: 3,
    pleasant: 0.83,
    tension: 0.37,
    energy: 0.38,
    date: '2019-03-04',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Less than usual',
    sun: 4,
    relax: 'Less than usual',
    exercise: false,
    work: 3,
    meals: 3,

    pleasant: 0.21,
    tension: 0.94,
    energy: 0.21,
    date: '2019-03-05',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 4,
    relax: 'More than usual',
    exercise: false,
    work: 3,
    meals: 1,

    pleasant: 0.82,
    tension: 0.79,
    energy: 0.86,
    date: '2019-03-06',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'More than usual',
    sun: 1,
    relax: 'Usual amount',
    exercise: false,
    work: 3,
    meals: 0,

    pleasant: 0.78,
    tension: 0.81,
    energy: 0.13,
    date: '2019-03-07',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 5,
    relax: 'Usual amount',
    exercise: false,
    work: 5,
    meals: 3,

    pleasant: 0.85,
    tension: 0.49,
    energy: 0.4,
    date: '2019-03-08',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Less than usual',
    sun: 3,
    relax: 'Usual amount',
    exercise: false,
    work: 4,
    meals: 1,

    pleasant: 0.75,
    tension: 0.34,
    energy: 0.92,
    date: '2019-03-09',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 2,
    relax: 'Less than usual',
    exercise: false,
    work: 4,
    meals: 3,

    pleasant: 0.72,
    tension: 0.74,
    energy: 0.62,
    date: '2019-03-10',
    userId: 3
  },
  {
    sleep: '4-6',
    social: 'Less than usual',
    sun: 4,
    relax: 'Less than usual',
    exercise: false,
    work: 3,
    meals: 2,

    pleasant: 0.66,
    tension: 0.35,
    energy: 0.7,
    date: '2019-03-11',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'More than usual',
    sun: 4,
    relax: 'Not at all',
    exercise: false,
    work: 4,
    meals: 3,

    pleasant: 0.58,
    tension: 0.94,
    energy: 0.83,
    date: '2019-03-12',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Not at all',
    sun: 3,
    relax: 'More than usual',
    exercise: false,
    work: 0,
    meals: 2,

    pleasant: 0.75,
    tension: 0.13,
    energy: 0.63,
    date: '2019-03-13',
    userId: 3
  },
  {
    sleep: '4-6',
    social: 'More than usual',
    sun: 4,
    relax: 'Less than usual',
    exercise: false,
    work: 3,
    meals: 2,

    pleasant: 0.68,
    tension: 0.85,
    energy: 0.6,
    date: '2019-03-14',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 3,
    relax: 'Less than usual',
    exercise: true,
    work: 5,
    meals: 4,

    pleasant: 0.6,
    tension: 0.53,
    energy: 0.69,
    date: '2019-03-15',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'More than usual',
    sun: 2,
    relax: 'Usual amount',
    exercise: true,
    work: 5,
    meals: 3,

    pleasant: 1,
    tension: 0.87,
    energy: 0.69,
    date: '2019-03-16',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 3,
    relax: 'Usual amount',
    exercise: false,
    work: 4,
    meals: 2,

    pleasant: 0.75,
    tension: 0.69,
    energy: 0.49,
    date: '2019-03-17',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 0,
    relax: 'Usual amount',
    exercise: false,
    work: 3,
    meals: 3,

    pleasant: 0.61,
    tension: 0.97,
    energy: 1,
    date: '2019-03-18',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Less than usual',
    sun: 0,
    relax: 'Usual amount',
    exercise: true,
    work: 4,
    meals: 2,

    pleasant: 0.91,
    tension: 0.26,
    energy: 0.85,
    date: '2019-03-19',
    userId: 3
  },
  {
    sleep: '4-6',
    social: 'Usual amount',
    sun: 5,
    relax: 'Less than usual',
    exercise: true,
    work: 5,
    meals: 1,

    pleasant: 0.88,
    tension: 0.88,
    energy: 0.92,
    date: '2019-03-20',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 3,
    relax: 'Less than usual',
    exercise: false,
    work: 3,
    meals: 3,

    pleasant: 0.71,
    tension: 0.65,
    energy: 0.63,
    date: '2019-03-21',
    userId: 3
  },
  {
    sleep: '2-4',
    social: 'Usual amount',
    sun: 2,
    relax: 'Usual amount',
    exercise: false,
    work: 3,
    meals: 3,

    pleasant: 0.69,
    tension: 0.6,
    energy: 0.25,
    date: '2019-03-22',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 5,
    relax: 'Less than usual',
    exercise: false,
    work: 4,
    meals: 2,

    pleasant: 0.72,
    tension: 0.56,
    energy: 0.66,
    date: '2019-03-23',
    userId: 3
  },
  {
    sleep: '0-2',
    social: 'Less than usual',
    sun: 3,
    relax: 'More than usual',
    exercise: false,
    work: 3,
    meals: 2,

    pleasant: 0.65,
    tension: 0.35,
    energy: 0.36,
    date: '2019-03-24',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Less than usual',
    sun: 4,
    relax: 'Less than usual',
    exercise: true,
    work: 3,
    meals: 2,

    pleasant: 0.77,
    tension: 0.34,
    energy: 0.75,
    date: '2019-03-25',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 5,
    relax: 'Less than usual',
    exercise: true,
    work: 3,
    meals: 3,

    pleasant: 0.92,
    tension: 0.71,
    energy: 0.58,
    date: '2019-03-26',
    userId: 3
  },
  {
    sleep: '2-4',
    social: 'More than usual',
    sun: 4,
    relax: 'Less than usual',
    exercise: false,
    work: 2,
    meals: 3,

    pleasant: 0.55,
    tension: 0.87,
    energy: 0.53,
    date: '2019-03-27',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 4,
    relax: 'Less than usual',
    exercise: false,
    work: 4,
    meals: 3,

    pleasant: 0.62,
    tension: 0.46,
    energy: 0.28,
    date: '2019-03-28',
    userId: 3
  }
]

const harleyEvenings = [
  {
    sleep: '6-8',
    social: 'Not at all',
    sun: 3,
    relax: 'More than usual',
    exercise: false,
    work: 3,
    meals: 3,
    tags: null,
    pleasant: 0.83,
    tension: 0.37,
    energy: 0.38,
    date: '2019-02-07',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Less than usual',
    sun: 4,
    relax: 'Less than usual',
    exercise: false,
    work: 3,
    meals: 3,
    tags: null,
    pleasant: 0.21,
    tension: 0.34,
    energy: 0.21,
    date: '2019-02-08',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 4,
    relax: 'More than usual',
    exercise: false,
    work: 3,
    meals: 1,
    tags: null,
    pleasant: 0.82,
    tension: 0.59,
    energy: 0.86,
    date: '2019-02-09',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'More than usual',
    sun: 1,
    relax: 'Usual amount',
    exercise: false,
    work: 3,
    meals: 0,
    tags: null,
    pleasant: 0.78,
    tension: 0.91,
    energy: 0.13,
    date: '2019-02-10',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 5,
    relax: 'Usual amount',
    exercise: false,
    work: 5,
    meals: 3,
    tags: null,
    pleasant: 0.85,
    tension: 0.59,
    energy: 0.4,
    date: '2019-02-11',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Less than usual',
    sun: 3,
    relax: 'Usual amount',
    exercise: false,
    work: 4,
    meals: 1,
    tags: null,
    pleasant: 0.75,
    tension: 0.44,
    energy: 0.92,
    date: '2019-02-12',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 2,
    relax: 'Less than usual',
    exercise: false,
    work: 4,
    meals: 3,
    tags: null,
    pleasant: 0.72,
    tension: 0.54,
    energy: 0.62,
    date: '2019-02-13',
    userId: 3
  },
  {
    sleep: '4-6',
    social: 'Less than usual',
    sun: 4,
    relax: 'Less than usual',
    exercise: false,
    work: 3,
    meals: 2,
    tags: null,
    pleasant: 0.66,
    tension: 0.45,
    energy: 0.7,
    date: '2019-02-14',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'More than usual',
    sun: 4,
    relax: 'Not at all',
    exercise: false,
    work: 4,
    meals: 3,
    tags: null,
    pleasant: 0.58,
    tension: 0.94,
    energy: 0.83,
    date: '2019-02-15',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Not at all',
    sun: 3,
    relax: 'More than usual',
    exercise: false,
    work: 0,
    meals: 2,
    tags: null,
    pleasant: 0.75,
    tension: 0.93,
    energy: 0.63,
    date: '2019-02-16',
    userId: 3
  },
  {
    sleep: '4-6',
    social: 'More than usual',
    sun: 4,
    relax: 'Less than usual',
    exercise: false,
    work: 3,
    meals: 2,
    tags: null,
    pleasant: 0.68,
    tension: 0.95,
    energy: 0.6,
    date: '2019-02-17',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 3,
    relax: 'Less than usual',
    exercise: true,
    work: 5,
    meals: 4,
    tags: null,
    pleasant: 0.6,
    tension: 0.43,
    energy: 0.69,
    date: '2019-02-18',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'More than usual',
    sun: 2,
    relax: 'Usual amount',
    exercise: true,
    work: 5,
    meals: 3,
    tags: null,
    pleasant: 1,
    tension: 0.97,
    energy: 0.69,
    date: '2019-02-19',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 3,
    relax: 'Usual amount',
    exercise: false,
    work: 4,
    meals: 2,
    tags: null,
    pleasant: 0.75,
    tension: 0.69,
    energy: 0.49,
    date: '2019-02-20',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 0,
    relax: 'Usual amount',
    exercise: false,
    work: 3,
    meals: 3,
    tags: null,
    pleasant: 0.61,
    tension: 0.57,
    energy: 1,
    date: '2019-02-21',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Less than usual',
    sun: 0,
    relax: 'Usual amount',
    exercise: true,
    work: 4,
    meals: 2,
    tags: null,
    pleasant: 0.91,
    tension: 0.36,
    energy: 0.85,
    date: '2019-02-22',
    userId: 3
  },
  {
    sleep: '4-6',
    social: 'Usual amount',
    sun: 5,
    relax: 'Less than usual',
    exercise: true,
    work: 5,
    meals: 1,
    tags: null,
    pleasant: 0.88,
    tension: 0.48,
    energy: 0.92,
    date: '2019-02-23',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 3,
    relax: 'Less than usual',
    exercise: false,
    work: 3,
    meals: 3,
    tags: null,
    pleasant: 0.71,
    tension: 0.55,
    energy: 0.63,
    date: '2019-02-24',
    userId: 3
  },
  {
    sleep: '2-4',
    social: 'Usual amount',
    sun: 2,
    relax: 'Usual amount',
    exercise: false,
    work: 3,
    meals: 3,
    tags: null,
    pleasant: 0.69,
    tension: 0.6,
    energy: 0.25,
    date: '2019-02-25',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 5,
    relax: 'Less than usual',
    exercise: false,
    work: 4,
    meals: 2,
    tags: null,
    pleasant: 0.72,
    tension: 0.56,
    energy: 0.66,
    date: '2019-02-26',
    userId: 3
  },
  {
    sleep: '0-2',
    social: 'Less than usual',
    sun: 3,
    relax: 'More than usual',
    exercise: false,
    work: 3,
    meals: 2,
    tags: null,
    pleasant: 0.65,
    tension: 0.35,
    energy: 0.36,
    date: '2019-02-27',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Less than usual',
    sun: 4,
    relax: 'Less than usual',
    exercise: true,
    work: 3,
    meals: 2,
    tags: null,
    pleasant: 0.77,
    tension: 0.34,
    energy: 0.75,
    date: '2019-02-28',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 5,
    relax: 'Less than usual',
    exercise: true,
    work: 3,
    meals: 3,
    tags: null,
    pleasant: 0.92,
    tension: 0.71,
    energy: 0.58,
    date: '2019-03-01',
    userId: 3
  },
  {
    sleep: '2-4',
    social: 'More than usual',
    sun: 4,
    relax: 'Less than usual',
    exercise: false,
    work: 2,
    meals: 3,
    tags: null,
    pleasant: 0.55,
    tension: 0.97,
    energy: 0.53,
    date: '2019-03-02',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 4,
    relax: 'Less than usual',
    exercise: false,
    work: 4,
    meals: 3,
    tags: null,
    pleasant: 0.62,
    tension: 0.46,
    energy: 0.28,
    date: '2019-03-03',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Not at all',
    sun: 3,
    relax: 'More than usual',
    exercise: false,
    work: 3,
    meals: 3,
    tags: null,
    pleasant: 0.83,
    tension: 0.37,
    energy: 0.38,
    date: '2019-03-04',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Less than usual',
    sun: 4,
    relax: 'Less than usual',
    exercise: false,
    work: 3,
    meals: 3,
    tags: null,
    pleasant: 0.21,
    tension: 0.34,
    energy: 0.21,
    date: '2019-03-05',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 4,
    relax: 'More than usual',
    exercise: false,
    work: 3,
    meals: 1,
    tags: null,
    pleasant: 0.82,
    tension: 0.59,
    energy: 0.86,
    date: '2019-03-06',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'More than usual',
    sun: 1,
    relax: 'Usual amount',
    exercise: false,
    work: 3,
    meals: 0,
    tags: null,
    pleasant: 0.78,
    tension: 0.91,
    energy: 0.13,
    date: '2019-03-07',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 5,
    relax: 'Usual amount',
    exercise: false,
    work: 5,
    meals: 3,
    tags: null,
    pleasant: 0.85,
    tension: 0.59,
    energy: 0.4,
    date: '2019-03-08',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Less than usual',
    sun: 3,
    relax: 'Usual amount',
    exercise: false,
    work: 4,
    meals: 1,
    tags: null,
    pleasant: 0.75,
    tension: 0.44,
    energy: 0.92,
    date: '2019-03-09',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 2,
    relax: 'Less than usual',
    exercise: false,
    work: 4,
    meals: 3,
    tags: null,
    pleasant: 0.72,
    tension: 0.54,
    energy: 0.62,
    date: '2019-03-10',
    userId: 3
  },
  {
    sleep: '4-6',
    social: 'Less than usual',
    sun: 4,
    relax: 'Less than usual',
    exercise: false,
    work: 3,
    meals: 2,
    tags: null,
    pleasant: 0.66,
    tension: 0.45,
    energy: 0.7,
    date: '2019-03-11',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'More than usual',
    sun: 4,
    relax: 'Not at all',
    exercise: false,
    work: 4,
    meals: 3,
    tags: null,
    pleasant: 0.58,
    tension: 0.94,
    energy: 0.83,
    date: '2019-03-12',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Not at all',
    sun: 3,
    relax: 'More than usual',
    exercise: false,
    work: 0,
    meals: 2,
    tags: null,
    pleasant: 0.75,
    tension: 0.93,
    energy: 0.63,
    date: '2019-03-13',
    userId: 3
  },
  {
    sleep: '4-6',
    social: 'More than usual',
    sun: 4,
    relax: 'Less than usual',
    exercise: false,
    work: 3,
    meals: 2,
    tags: null,
    pleasant: 0.68,
    tension: 0.95,
    energy: 0.6,
    date: '2019-03-14',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 3,
    relax: 'Less than usual',
    exercise: true,
    work: 5,
    meals: 4,
    tags: null,
    pleasant: 0.6,
    tension: 0.43,
    energy: 0.69,
    date: '2019-03-15',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'More than usual',
    sun: 2,
    relax: 'Usual amount',
    exercise: true,
    work: 5,
    meals: 3,
    tags: null,
    pleasant: 1,
    tension: 0.97,
    energy: 0.69,
    date: '2019-03-16',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 3,
    relax: 'Usual amount',
    exercise: false,
    work: 4,
    meals: 2,
    tags: null,
    pleasant: 0.75,
    tension: 0.69,
    energy: 0.49,
    date: '2019-03-17',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 0,
    relax: 'Usual amount',
    exercise: false,
    work: 3,
    meals: 3,
    tags: null,
    pleasant: 0.61,
    tension: 0.57,
    energy: 1,
    date: '2019-03-18',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Less than usual',
    sun: 0,
    relax: 'Usual amount',
    exercise: true,
    work: 4,
    meals: 2,
    tags: null,
    pleasant: 0.91,
    tension: 0.36,
    energy: 0.85,
    date: '2019-03-19',
    userId: 3
  },
  {
    sleep: '4-6',
    social: 'Usual amount',
    sun: 5,
    relax: 'Less than usual',
    exercise: true,
    work: 5,
    meals: 1,
    tags: null,
    pleasant: 0.88,
    tension: 0.48,
    energy: 0.92,
    date: '2019-03-20',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 3,
    relax: 'Less than usual',
    exercise: false,
    work: 3,
    meals: 3,
    tags: null,
    pleasant: 0.71,
    tension: 0.55,
    energy: 0.63,
    date: '2019-03-21',
    userId: 3
  },
  {
    sleep: '2-4',
    social: 'Usual amount',
    sun: 2,
    relax: 'Usual amount',
    exercise: false,
    work: 3,
    meals: 3,
    tags: null,
    pleasant: 0.69,
    tension: 0.6,
    energy: 0.25,
    date: '2019-03-22',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 5,
    relax: 'Less than usual',
    exercise: false,
    work: 4,
    meals: 2,
    tags: null,
    pleasant: 0.72,
    tension: 0.56,
    energy: 0.66,
    date: '2019-03-23',
    userId: 3
  },
  {
    sleep: '0-2',
    social: 'Less than usual',
    sun: 3,
    relax: 'More than usual',
    exercise: false,
    work: 3,
    meals: 2,
    tags: null,
    pleasant: 0.65,
    tension: 0.35,
    energy: 0.36,
    date: '2019-03-24',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Less than usual',
    sun: 4,
    relax: 'Less than usual',
    exercise: true,
    work: 3,
    meals: 2,
    tags: null,
    pleasant: 0.77,
    tension: 0.34,
    energy: 0.75,
    date: '2019-03-25',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 5,
    relax: 'Less than usual',
    exercise: true,
    work: 3,
    meals: 3,
    tags: null,
    pleasant: 0.92,
    tension: 0.71,
    energy: 0.58,
    date: '2019-03-26',
    userId: 3
  },
  {
    sleep: '2-4',
    social: 'More than usual',
    sun: 4,
    relax: 'Less than usual',
    exercise: false,
    work: 2,
    meals: 3,
    tags: null,
    pleasant: 0.55,
    tension: 0.97,
    energy: 0.53,
    date: '2019-03-27',
    userId: 3
  },
  {
    sleep: '6-8',
    social: 'Usual amount',
    sun: 4,
    relax: 'Less than usual',
    exercise: false,
    work: 4,
    meals: 3,
    tags: null,
    pleasant: 0.62,
    tension: 0.46,
    energy: 0.28,
    date: '2019-03-28',
    userId: 3
  }
]
